% load 0, demand 20, storage half_full, wind speed 5. 

c_max(w, 10).
c_max(psh, 15).
c_max(f, 20).

control(c).
windmill(w).
storage_plant(psh).
caloric_plant(f).

c(c, i1, 0).
c(c, i2, 20).
c(c, i3, half_full).
c(c, i4, 5).

expect_c(c, i1, 0).
expect_c(c, i2, 20).
expect_c(c, i3, half_full).
expect_c(c, i4, 5).

expect_c(c, o1, 10).
expect_c(c, o2, 10).
expect_c(c, o3, 0).
expect_c(c, o4, 1).
expect_c(c, o5, 0).
