p(W, op, 0) :- windmill(W), c(W, iw, Wind), Wind < 5, not ab(W).
p(W, op, 0) :- windmill(W), c(W, iw, Wind), Wind > 40, not ab(W).
p(W, op, X) :- windmill(W), c(W, iw, Wind), c(W, i1, X),
               c_max(W, MaxCap), X <= MaxCap, X >= 0,
               Wind >= 5, Wind <= 40,
               not ab(W).
p(W, op, MaxCap) :- windmill(W), c(W, iw, Wind), c(W, i1, X),
                    c_max(W, MaxCap), X > MaxCap,
                    Wind >= 5, Wind <= 40,
                    not ab(W).
