%Author: Christopher Simerle

% Storage = full
% Wind = reicht

% • c max(psh, 20) defines the maximal capacity of the storage plant,
% • c max(w, 15) defines the maximal capacity of the windmill,
% • c max(f, 60) defines the maximal capacity of the fossil-fuel plant, and
% • w charge(30) defines the maximal charging capacity of the storage plants.

% storage plant, windmill und fossil fuel produzieren

in_c(s_storage, full).
in_c(s_wind, 20).
in_c(l_demand, 50).
in_c(l_current, 10).
in_p(p_in, 10).
expect_out_p(p_out, 50).