%Author: Christopher Simerle

% Storage = empty
% Wind = reicht nicht

% • c max(psh, 20) defines the maximal capacity of the storage plant,
% • c max(w, 15) defines the maximal capacity of the windmill,
% • c max(f, 60) defines the maximal capacity of the fossil-fuel plant, and
% • w charge(30) defines the maximal charging capacity of the storage plants.

% windmill produziert

in_c(s_storage, full).
in_c(s_wind, 30).
in_c(l_demand, 15).
in_c(l_current, 10).
in_p(p_in, 10).
expect_out_p(p_out, 15).