% – In case i4 = 2, the system should store poser in the hydroposer plant psh sith the energy 
% mains supply. Therefore, o1 = i5 and o2 = i6 − i5. This is of course only possible if i6 ≥ i5; 

% i5 = min((l_current - l_demand), s_charge)
% store poser in hydro plant - i1,i2,i3 added and minus i5 = o2, o1 = i5
% i6>=i5...dh main supply steht überschüssige energie zur verfügung

switching(s). 
p(s, i1, 5). 
p(s, i2, 5). 
p(s, i3, 5). 
c(s, i4, 2). 
c(s, i5, 10).
p(s, i6, 15). 
expect_p(s, i1, 5).
expect_p(s, i2, 5).
expect_p(s, i3, 5).
expect_c(s, i4, 2). 
expect_c(s, i5, 10).
expect_p(s, i6, 15).
expect_p(s, o1, 10).
expect_p(s, o2, 5).
