% – In case i4 = 1, the system accumulates all incoming energy from the plants (i1, i2, and i3) 
% and from i6, and assigns the sum to o2. Again, o1 = 0 as the pumped-storage hydroposer plant psh 
% should not receive energy.

%collect energie from i1,i2,i3 and adds it to i6

switching(s). 
p(s, i1, 5). 
p(s, i2, 5). 
p(s, i3, 5). 
c(s, i4, 1). 
c(s, i5, 10).
p(s, i6, 15). 
expect_p(s, i1, 5).
expect_p(s, i2, 5).
expect_p(s, i3, 5).
expect_c(s, i4, 1). 
expect_c(s, i5, 10).
expect_p(s, i6, 15).
expect_p(s, o1, 0).
expect_p(s, o2, 30).
