% --------------------------------------
%	Manuel Stadler
%	0926556
%	Tu Wien - SS 12
%
%	Test for control
%
% --------------------------------------

control(c).
windmill(w).
caloric_plant(f).
storage_plant(psh).

c(c,i1,20).
c(c,i2,20).
c(c,i3,full).
c(c,i4,30).

c_max(w, 10).
c_max(f, 10).
c_max(psh, 10).
w_charge(30).

expect_c(c,i1,20).
expect_c(c,i2,20).
expect_c(c,i3,full).
expect_c(c,i4,30).

expect_c(c, o1, 0).
expect_c(c, o2, 0).
expect_c(c, o3, 0).
expect_c(c, o4, 0).
expect_c(c, o5, 0).