% --------------------------------------
%	Manuel Stadler
%	0926556
%	Tu Wien - SS 12
%
%	Test for control
%
% --------------------------------------

control(c).
windmill(w).
caloric_plant(f).
storage_plant(psh).

c(c,i1,10).
c(c,i2,40).
c(c,i3,half_full).
c(c,i4,0).

c_max(w, 10).
c_max(f, 20).
c_max(psh, 10).
w_charge(30).

expect_c(c,i1,10).
expect_c(c,i2,40).
expect_c(c,i3,half_full).
expect_c(c,i4,0).

expect_c(c, o1, 10).
expect_c(c, o2, 0).
expect_c(c, o3, 20).
expect_c(c, o4, 1).
expect_c(c, o5, 0).