% --------------------------------------
%	Manuel Stadler
%	0926556
%	Tu Wien - SS 12
%
%	Test for switching station
% --------------------------------------

switching(s). 

p(s, i1, 10). 
p(s, i2, 10). 
p(s, i3, 10). 
c(s, i4, 1). 
c(s, i5, 0).
p(s, i6, 15). 

expect_p(s, i1, 10).
expect_p(s, i2, 10).
expect_p(s, i3, 10).
expect_c(s, i4, 1). 
expect_c(s, i5, 0).
expect_p(s, i6, 15).

expect_p(s, o1, 0).
expect_p(s, o2, 45).