% --------------------------------------
%	Manuel Stadler
%	0926556
%	Tu Wien - SS 12
%
%	Test for switching station
% --------------------------------------

switching(s). 

p(s, i1, 0). 
p(s, i2, 0). 
p(s, i3, 0). 
c(s, i4, 2). 
c(s, i5, 20).
p(s, i6, 15). 

expect_p(s, i1, 0).
expect_p(s, i2, 0).
expect_p(s, i3, 0).
expect_c(s, i4, 2). 
expect_c(s, i5, 20).
expect_p(s, i6, 15).

expect_p(s, o1, 15).
expect_p(s, o2, 0).